build:
  image: golang
  commands:
    - go get -t -v ./...
    - cp config.yaml.travis config.yaml
    - ./go.test.sh
    - bash <(curl -s https://codecov.io/bash)
    
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=rfag
