build:
  image: golang
  environment:
    - CODECOV_TOKEN=$$CODECOV_TOKEN
  commands:
    - go get -t -v ./...
    - cp config.yaml.drone config.yaml
    - ./go.test.sh
    - curl -s https://codecov.io/bash > .codecov
    - chmod +x .codecov
    - ./.codecov

compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=rfag
