language: go

services:
    - postgresql

go:
    - 1.7.3

before_script:
    - go get -t -v ./...
    - psql -c 'create database rfag;' -U postgres
    - cp config.yaml.travis config.yaml

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)