language: go

services:
    - postgresql

go:
    - 1.7.3

before_script:
    - go get -t -v ./...
    - psql -c 'create database posts;' -U postgres
    - cp config.yaml.travis config.yaml

script:
    - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)